name: Release and Publish to Both Registries
# some people say AI is smart!
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      # NEW STEP: Create .npmrc file for authentication
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_TOKEN }}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Build Project
        run: bun run build

      - name: Release
        run: npx semantic-release
        env:
          # We don't need to pass the tokens here anymore because .npmrc handles it
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
